### ISSUE TITLE
Replace deprecated String.strip/1 with String.trim/1

### ISSUE THREAD

**Issue by kipcole9** [elixir-plug/mime#24]
On Elixir 1.5.x and 1.6-rc mime 1.1.0  issues a compiler warning
```elixir
==> mime
Compiling 1 file (.ex)
warning: String.strip/1 is deprecated, use String.trim/1
  lib/mime.ex:28
```
Are you open to a PR or is backwards compatibility constrained until Elixir 2.0?

**Comment by josevalim** [comment]
We had fixed it but no release was made. v1.2.0 is out now!
