### ISSUE TITLE
Compile Warning on Elixir 1.8.0-otp-21.2.2

### ISSUE THREAD

**Issue by OvermindDL1** [elixir-plug/mime#32]
```elixir
==> mime
Compiling 2 files (.ex)
warning: this clause cannot match because a previous clause at line 2 always matches
  lib/mime.ex:2

Generated mime app
```
Looks like it's in the generated code.

**Comment by josevalim** [comment]
Thanks! Note I don't get it on 21.2 so it is probably a more recent warning on OTP side of things. I will investigate it later.

**Comment by OvermindDL1** [comment]
> Thanks! Note I don't get it on 21.2 so it is probably a more recent warning on OTP side of things. I will investigate it later.

Yep, I'm running 21.2.2 freshly built, been upgrading the main build server from 20 (with elixir 1.6) and trying to get everything to compile cleanly as the pre-prod server compiles with warnings as errors globally so I'm reporting a lot of errors/warnings around to the latest versions of packages today.  ^.^;

**Comment by jaimeiniesta** [comment]
I'm also getting this warning on Elixir 1.10.4 with OTP 23.
