### ISSUE TITLE
Add MIME type for .aac files

### ISSUE THREAD

**Issue by rageofflames** [elixir-plug/mime#34]
It is possible to support aac audio files by extending the mime types config.

```
config :mime, :types, %{
  "audio/aac" => ["aac"]
}
```

Should this type be integrated into the static mime types file?

@josevalim if this makes sense I will create a PR that adds the aac type

**Comment by josevalim** [comment]
Hi @rageofflames! To make things simpler, we just keep a copy of the MIME database from Apache. So if the database added it, then we can copy it’s latest version, otherwise you should add it yourself. Thanks!

**Comment by rageofflames** [comment]
@josevalim makes sense 👍Thank you for the quick answer.

Where are you getting the MIME database from Apache? https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types this one appears to contain the aac extension

**Comment by josevalim** [comment]
So it seems we moved to this one: https://pagure.io/mailcap/blob/master/f/mime.types

We could migrate to apache but we need to see if nothing would be removed in the process. Can you please try a PR?
