### ISSUE TITLE
Casing issues with some mimes

### ISSUE THREAD

**Issue by IceDragon200** [elixir-plug/mime#38]
The fatest way to demonstrate the problem:

```elixir
iex(2)> MIME.extensions("audio/amr")
[]
iex(3)> MIME.extensions("audio/AMR")
["amr"]
```

I believe MIME should at least normalize (lowercase) all it's compiled types, and possibly lowercase it's input to match, unless the latter creates a performance issue

__Expectation__

`MIME.extensions/1` works with any casing thrown at it

**Comment by josevalim** [comment]
You are correct, the spec says they are not case sensitive, we should probably include both in such cases.

**Comment by josevalim** [comment]
Btw, a PR is welcome!

**Comment by IceDragon200** [comment]
Sure thing, I'll have one up shortly
