### ISSUE TITLE
Unsupported default browser Accept values

### ISSUE THREAD

**Issue by Lucassifoni** [elixir-plug/mime#49]
Hello,
I started getting errors reported in Sentry for various Safari versions requesting **image/\*** in Accept headers.
To my surprise, this value is known as a default for at least Firefox and Safari as shown on this page : 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation/List_of_default_Accept_values

I'm unsure if this package should support this, as **it cannot be used to directly map a type to a file extension**.
But by default, Phoenix 1.5.0 errors out when an image is requested with only image/* in an Accept header, and according to my Sentry log, this is quite common. I could of course work around this by configuring MIME in my config.exs

I apologize if this is not the right project to open an issue on, but if that would be the case, where could this edge-case be handled ?
Have a nice day,
Lucas

**Comment by josevalim** [comment]
Can you please provide a full stacktrace of the exception you are getting? I don't think this would be handled here but I need more information to be sure.

**Comment by Lucassifoni** [comment]
Hello José, thank you for your quick answer.
Here are more details : 

```
Phoenix.NotAcceptableError: no supported media type in accept header.

Expected one of ["html", "json"] but got the following formats:

  * "image/*" with extensions: "image"

To accept custom formats, register them under the :mime library
in your config/config.exs file:

    config :mime, :types, %{
      "application/xml" => ["xml"]
    }

And then run `mix deps.clean --build mime` to force it to be recompiled.

  File "lib/phoenix/controller.ex", line 1313, in Phoenix.Controller.refuse/3
  Module "Elixir.TextileWeb.Router", in TextileWeb.Router.browser/2
  File "lib/textile_web/router.ex", line 1, in TextileWeb.Router.__pipe_through0__/1
    defmodule TextileWeb.Router do
  File "lib/phoenix/router.ex", line 347, in Phoenix.Router.__call__/2
  File "lib/plug/error_handler.ex", line 65, in TextileWeb.Router.call/2
  File "lib/textile_web/endpoint.ex", line 1, in TextileWeb.Endpoint.plug_builder_call/2
    defmodule TextileWeb.Endpoint do
  File "lib/textile_web/endpoint.ex", line 1, in TextileWeb.Endpoint."call (overridable 3)"/2
    defmodule TextileWeb.Endpoint do
  File "lib/textile_web/endpoint.ex", line 1, in TextileWeb.Endpoint.call/2
    defmodule TextileWeb.Endpoint do
```

Here's the request in CURL format

```
curl \
 --compressed \
 -H "Accept: image/*" \
 -H "Accept-Encoding: gzip" \
 -H "Connection: close" \
 -H "Host: localhost:4003" \
 -H "User-Agent: willnorris/imageproxy" \
 "http://localhost:4003/picture/dynamic/2020/07/-eHPAuDPAZLGRlrazTBd-vE76SVvH4.jpg?size=4000"
```

It seems that I overlooked that imageproxy (this project: https://github.com/willnorris/imageproxy ) generates the request, however I only have occurences for users of Safari 13.1 in Sentry logs.

**Comment by josevalim** [comment]
It is all working as expected. Your application says it can only handle html/json, and someone is requesting an image, so your application is correctly saying that it can't fullfil that request and is returning a 406, as expected by HTTP.

**Comment by Lucassifoni** [comment]
Well, I'm then sorry for the lost time, there's something I did not understand right in this process.
