### ISSUE TITLE
audio/3gpp has no extensions causing MIME.has_type?/1 to always return false

### ISSUE THREAD

**Issue by IceDragon200** [elixir-plug/mime#50]
It's causing a few issues at the moment, for one because it has no extensions `MIME.has_type?/1` returns false:

```
iex(1)> MIME.has_type?("audio/3gpp")
false
```

I've quickly scanned the mime.types and it is listed without extensions: https://github.com/elixir-plug/mime/blob/master/priv/mime.types#L1512

I'm sure other types have this same issue as well, I'm not sure what should be added to the existing API to support cases like this where a type can exist, even without known extensions:

```elixir
iex(1)> MIME.type?("audio/3gpp")
false
iex(2)> MIME.type_exists?("audio/3gpp")
true
```

**Comment by josevalim** [comment]
We follow a known database of types, there is a link in the source file. so I would recommend getting your suggestion upstream and then we can merge it. Meanwhile, you can configure the library with custom types and extensions, please check the docs. :)
