### ISSUE TITLE
Change in file extensions of text/plain

### ISSUE THREAD

**Issue by prehnRA** [elixir-plug/mime#58]
Hello there. I have a question for you.

I noticed that the extensions returned by `MIME.extensions("text/plain")` has changed between 1.6.0 and 2.0.0. In 1.6.0, the return value is `["txt", "asc", "text", "pm", "el", "c", "h", "cc", "hh", "cxx", "hxx", "f90", "conf", "log"]`. In 2.0.0, it is `["txt"]`.

Is this intentional? I had trouble verifying what to expect from the IANA data.

**Comment by josevalim** [comment]
Yes, it is intentional. We removed the IANA dataset instead of a minimal one.
