### ISSUE TITLE
Simplify validating incoming MIME types

### ISSUE THREAD

**Issue by s3cur3** [elixir-plug/mime#69]
I'm trying to validate incoming MIME types are of a given document type. That is, I download what is _theoretically_ an image, and I'd like to:

1. Verify that its `Content-Type` header matches a known `image/*` type
2. Verify that its file extension matches its MIME type

Both are possible now, but a little roundabout.

1. For verifying a MIME type is a known `image/*` type, you can do something like:

    ```
    known_image_type? =
      with "image/" <> _ <- mime_type,
           extensions when extensions != [] <- MIME.extensions(mime_type) do
        true
      else
        false
      end
    ```

    I think it'd be really cool if `MIME.extensions/1` supported partial MIME types (e.g., either `"image/"` or `"image/*"`)

2. Checking that the given file extension is known for a MIME type is even more roundabout. Something like:
    ```
    given_extension =
      image.filename
      |> Path.extname()
      |> String.replace(".", "")
      |> String.downcase()

    extension_matches_mime_type? = given_extension in MIME.extensions(image.content_type)
    ```

    This one strikes me as being worth a new top-level function... something like `MIME.path_matches_type?(path, mime_type)`

I'm happy to submit a PR if this is something you all are interested in. ☺️

**Comment by josevalim** [comment]
I would prefer to not support 1 because it makes all lookups more expensive as we know need to check if we didn't receive a partial element. I think your solution looks great.

For 2, could you do this instead? `MIME.from_path(image.filename) == image.content_type`?

**Comment by s3cur3** [comment]
I think that breaks down for file extensions that could represent more than one MIME type. XML is one example: it could be `application/xml` or `text/xml`.

**Comment by josevalim** [comment]
Ah, good point. Yeah, i am not convinced at the moment we should add those features. Perhaps we could add `MIME.extname(path)` or similar that extracts the extension from a path as used by mime, so you could do:

    MIME.extname(path) in MIME.extensions(content_type)

But I think the other case is too specific.

**Comment by s3cur3** [comment]
Fair enough! ☺️
