### ISSUE TITLE
Strange behavior when adding a new type/extension

### ISSUE THREAD

**Issue by fedeotaran** [elixir-plug/mime#72]
Hi!

I have a question with the behavior when a new extension is added to a type.

For example, I want to add a new extension for a plain text file.

This type originally has the `txt` and `text` extensions added.
https://github.com/elixir-plug/mime/blob/9f3a9085dae559511b4c191438a3e24c944f2537/lib/mime.ex#L101

I add the new extension to my project according to the documentation:
```elixir
config :mime, :types, %{
  "text/plain" => ["env"]
}
```

The extensions now available for the `text/plain` type are as follows:
```bash
iex -S mix
Erlang/OTP 25 [erts-13.0.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.14.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> MIME.extensions("text/plain")
["env"]
iex(2)>
```

Which does not seem bad to me if what you are looking for is to overwrite all the extensions for that type.

But when looking at the type for the extensions separately, `text/plain` matches for all of them.
```bash
iex -S mix
Erlang/OTP 25 [erts-13.0.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.14.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> MIME.extensions("text/plain")
["env"]
iex(2)> MIME.type("txt")
"text/plain"
iex(3)> MIME.type("text")
"text/plain"
iex(4)> MIME.type("env")
"text/plain"
```

The `type/1` method works both old and new values.
This seems a bit confusing to me.

I think both options make sense, but it should be consistent for all methods.

What do you think?

I'm happy to send a PR if you think that's right 😄

**Comment by whatyouhide** [comment]
Yeah, this looks indeed confusing. I haven't even looked at the source code, but I think either we append configured extensions to existing ones (so that `MIME.extensions("text/plan") == ["txt", "text", "env"]`), or we overwrite `MIME.type/1` too. I'll let @josevalim pitch in.

**Comment by josevalim** [comment]
Yes, let's make sure we don't discard existing mime types. But the existing ones should always come at the end. Can you please PR?

**Comment by fedeotaran** [comment]
PR here #73 🙌🏽 

I applied an `Enum.uniq` to the list to avoid duplicates for those who had the configuration with the complete list before this change.

For example who configured like this:
```elixir
import Config

config :mime, :types, %{
  "text/plain" => ["env", "txt", "text"]
}
```
Otherwise, you will get the following result
```bash
iex -S mix
Erlang/OTP 25 [erts-13.0.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.14.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> MIME.extensions("text/plain")
["env", "txt", "text", "txt", "text"]
```

**Comment by aj-foster** [comment]
Hi folks! Thanks @fedeotaran for this PR. We just ran into the same issue, and I was excited to see you already tackled it.

Would it be possible to get a release of this library with the latest changes?
