### ISSUE TITLE
Request for New Release

### ISSUE THREAD

**Issue by aj-foster** [elixir-plug/mime#74]
Hi there 👋🏼 

With #73 you all helpfully fixed an issue we encountered. Would it be possible to create a new release that includes these changes?

Thank you!

**Comment by josevalim** [comment]
I dropped a comment on #73. I actually think we should revert because this changes makes it impossible to delete or change existing entries. Instead, we should customize that it overrides.

**Comment by josevalim** [comment]
Sorry for the confusion. I pushed a commit that allows it to be overridden instead.
