### ISSUE TITLE
Cannot add new type with same extension from the list on new version

### ISSUE THREAD

**Issue by ryvasquez** [elixir-plug/mime#77]
Hello Team! Thank you for this amazing library. However, we encountered an error when upgrading. To provide some background, we need to support the `audio/x-wav` type from the https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers#wave_wav. According to the documentation, `audio/x-wav` should also be recognized as `wav`.

Our configuration looks like this:

```
config :mime, :types, %{
  "audio/x-wav" => ["wav"]
}
```

In the previous version, `v2.0.3`, it worked as expected. However, when we tried to upgrade to `v2.0.4`, we received the following error message:

```
conflicting MIMEs for extension .wav, please override: ["audio/wav", "audio/x-wav"]
```

Upon investigation, I noticed similar types that share the same extension in the list, such as `3g2` and `3gp`. Prior to raising, these types are merged in the code section found here:
https://github.com/elixir-plug/mime/blob/90852eb1721fa891987cd8b3468830e03518c66f/lib/mime.ex#L139-L145

**Comment by josevalim** [comment]
Correct, you need to do this:

```elixir
config :mime, :types, %{
  "audio/wav" => [],
  "audio/x-wav" => ["wav"]
}
```

Or, if you want to keep wav returning the first, you do:

```elixir
config :mime, :types, %{
  "audio/x-wav" => []
}
```

It is just that "wav" cannot map to two mimes at once.

**Comment by josevalim** [comment]
Actually, that is bad feedback. Let me think about this.

**Comment by josevalim** [comment]
Please upgrade to v2.0.5 and the error message should tell you exactly what to do to fix it :)

**Comment by josevalim** [comment]
If it doesn't, please ping!

**Comment by ryvasquez** [comment]
@josevalim confirmed it now works in v2.0.5, thanks you for the quick fix and thanks for the informative error message!
